#!/bin/bash

#set -x

missing_something=false
data_police_home="$PWD"

file_to_load=""
header_to_use=""


#
# Select the right header
select_header() {

  case $file_to_load} in

    *-outcomes.csv)
    ;;

    *)
      echo
      echo "ERROR: Header not founf for ${file_to_load}"
      echo
      exit 0
    ;;

  esac

}


echo

# Checking if the zip file exists
if [ -z "${1}" ]; then

  echo "Missing file to unzip"
  missing_something=true

else

  zip_file="${1}.zip"

fi

#checking if the neo4j Home directory exists
if [ -z "${2}" ]; then
  
  echo "Missing Neo4j home directory."
  missing_something=true

fi

neo4j_home="${HOME}/release/${2}"
if [ ! -d "${neo4j_home}" ]; then
  
  echo "The Neo4j home directory does not exist."
  missing_something=true
fi

#checking if Neo4j is running
neo4j_check=`${neo4j_home}/bin/neo4j status`
if [ "${neo4j_check}" == "Neo4j is not running" ]; then
  
  echo "The Neo4j server is not running."
  missing_something=true

else

  #Createing the police database
  echo "Creating the police database..."
  ${neo4j_home}/bin/cypher-shell -d system -f ${data_police_home}/cypher/create_db.cypher

fi

if [ "${missing_something}" = true ]; then

  echo
  echo "Usage: ${0} YYYY-MM neo4j-home"
  echo "       YYYY       - year"
  echo "       MM         - month"
  echo "       neo4j-home - Home directory for Neo4j"
  echo
  echo "Example: ${0} 2020-02 403"
  echo

  exit 

fi
  
cd data
if [ -f "${zip_file}" ]; then

  echo
  echo "unzipping ${zip_file}"
  echo 
  #unzip "${zip_file}"

else

  echo 
  echo "The file ${zip_file} does not exist."
  echo 

fi

echo 
echo
echo "Loading data..."
echo

for load_dir in $( ls -d 20*/ )
do
  cd ${data_police_home}/data/${load_dir}
  for file_to_load in $( ls *csv ) 
  do
    echo "cp ${data_police_home}/cleansing-tools/headers/outcomes.header ${neo4j_home}/import/${file_to_load}"
    echo "tail -n +2 ${file_to_load} >> ${neo4j_home}/import/${file_to_load}"
    echo "rm ${neo4j_home}/import/${file_to_load}"
  done
done

exit 0

