#!/bin/bash

#set -x

data_police_home=`PWD`

if [ -z "${1}" ]; then

  echo
  echo "Usage: ${0} YYYY-MM"
  echo "       YYYY - year"
  echo "       MM   - month"
  echo "Example: ${0} 2020-02"
  echo
  exit 
  
else

  zip_file="${1}.zip"

fi

if [ -z "${2}" ]; then
  
  echo
  echo "Missing Neo4j home directory."
  echo
  exit

else

  neo4j_home="${HOME}/release/${2}"

fi

cd data
if [ -f "${zip_file}" ]; then

  echo
  echo "unzipping ${zip_file}"
  echo 
  #unzip "${zip_file}"

else

  echo 
  echo "The file ${zip_file} does not exist."
  echo 

fi

echo 
echo
echo "Loading data..."
echo

for load_dir in $( ls -d 20*/ )
do
  for file_to_load in $( ls ${load_dir}*csv ) 
  do
    echo "$file_to_load"
  done
done

exit 0
