#!/bin/bash

#set -x

if [ -z "${1}" ]; then

  echo
  echo "Usage: ${0} YYYY-MM"
  echo "       YYYY - year"
  echo "       MM   - month"
  echo "Example: ${0} 2020-02"
  echo
  exit 
  
else

  zip_file="${1}.zip"

fi

cd data

if [ -f "${zip_file}" ]; then

  echo
  echo "unzipping ${zip_file}"
  echo 
  unzip "${zip_file}"

else

  echo 
  echo "The file ${zip_file} does not exist."
  echo 

fi

exit 0
